In [1]:
%pylab inline
import pandas as pd
from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression

Populating the interactive namespace from numpy and matplotlib


D:\3kurs1sem\IDEs\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
D:\3kurs1sem\IDEs\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data = pd.read_csv(r'd:\3kurs1sem\semestrone\JUPYTER\Moscow\SMSSpamCollection.txt',sep='\t', header=None)

In [3]:
data.columns = ['labels','text']

In [4]:
data.shape

(5572, 2)

In [5]:
texts = data.text.values

In [6]:
texts.shape

(5572,)

In [7]:
labels = data.labels.values

In [8]:
labels = [1 if x == 'spam' else 0  for x in labels]


In [9]:
counter = CountVectorizer()

In [10]:
tf_vectorizer = CountVectorizer()
X = tf_vectorizer.fit_transform(texts)

In [11]:
cross_val_score(LogisticRegression(random_state=2),X,labels,cv=10,scoring='f1').mean()

0.9326402983610631

In [12]:
logreg = LogisticRegression(random_state=2)

In [13]:
logreg.fit(X,labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=2, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [14]:
ex1 = tf_vectorizer.transform(['FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GB'])

In [15]:
logreg.predict(ex1)

array([1])

In [16]:
ex2 = tf_vectorizer.transform(['FreeMsg: Txt: claim your reward of 3 hours talk time'])
logreg.predict(ex2)

array([1])

In [17]:
ex3 = tf_vectorizer.transform(['Have you visited the last lecture on physics?'])
logreg.predict(ex3)

array([0])

In [18]:
ex4 = tf_vectorizer.transform(["Have you visited the last lecture on physics? Just buy this book and you will have all materials! Only 99$"])
logreg.predict(ex4)

array([0])

In [19]:
ex5 = tf_vectorizer.transform(["Only 99$"])
logreg.predict(ex5)

array([0])

In [20]:
tf_vectorizer = CountVectorizer(ngram_range=(2,2))
X1 = tf_vectorizer.fit_transform(texts)
mean1 = cross_val_score(LogisticRegression(random_state=2),X1,labels,cv=10,scoring='f1').mean()
print(mean1)

tf_vectorizer = CountVectorizer(ngram_range=(3,3))
X2 = tf_vectorizer.fit_transform(texts)
mean2 = cross_val_score(LogisticRegression(random_state=2),X2,labels,cv=10,scoring='f1').mean()
print(mean2)

tf_vectorizer = CountVectorizer(ngram_range=(1,3))
X3 = tf_vectorizer.fit_transform(texts)
mean3 = cross_val_score(LogisticRegression(random_state=2),X3,labels,cv=10,scoring='f1').mean()
print(mean3)

0.8224220664187133
0.7250161555467377
0.9251382558648837


In [21]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [22]:
scores = cross_val_score(nb, X1, labels, cv=10, scoring='f1')
mean1 = np.mean(scores)

scores = cross_val_score(nb, X2, labels, cv=10, scoring='f1')
mean2= np.mean(scores)

scores = cross_val_score(nb, X3, labels, cv=10, scoring='f1')
mean3= np.mean(scores)

print ("%.2f %.2f %.2f" % (mean1, mean2, mean3))

0.65 0.38 0.89


In [23]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)
cross_val_score(LogisticRegression(random_state=2),X,labels,cv=10,scoring='f1').mean()

0.8528599554172456

In [24]:
X.toarray()[0].sum()


4.077455095433347